# CircleCI Configuration File
version: 2.1
jobs:
  build:
    working_directory: ~/preact-baby-names
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - preact-baby-names-cache-{{ checksum "yarn.lock" }}
            - preact-baby-names-cache-
      - run:
          name: Installing Dependencies
          command: yarn install
      - save_cache:
          name: Save Yarn Package Cache
          paths:
            - node_modules/
          key: preact-baby-names-cache-{{ checksum "yarn.lock" }}
      - run:
          name: Running Tests
          command: yarn test-ci
          no_output_timeout: "30s"
      - store_artifacts:
          path: coverage
          prefix: coverage
          when: on_success
workflows:
  version: 2.1
  build_and_test
    jobs:
      - build
