# CircleCI Configuration File
version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - restore_cache:
          name: Restore Npm Package Cache
          keys:
            - preact-baby-names-cache-{{ checksum "package-lock.json" }}
            - preact-baby-names-cache-
      - run:
          name: Installing Dependencies
          command: npm install
      - save_cache:
          name: Save Npm Package Cache
          paths:
            - node_modules/
          key: preact-baby-names-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Running Tests
          command: npm run test-ci
          no_output_timeout: "30s"
      - store_artifacts:
          path: coverage
          prefix: coverage
          when: on_success
  deploy:
    docker:
      - image: circleci/python:2.7-jessie
    steps:
      - checkout
      - run:
          name: Install AWS Cli
          command: sudo pip install awscli
      - run:
          name: "Update Node.js and npm"
          command: |
            curl -sSL "https://nodejs.org/dist/v11.10.0/node-v11.10.0-linux-x64.tar.xz" | sudo tar --strip-components=2 -xJ -C /usr/local/bin/ node-v11.10.0-linux-x64/bin/node
            curl https://www.npmjs.com/install.sh | sudo bash
      - restore_cache:
          name: Restore Npm Package Cache
          keys:
            - preact-baby-names-cache-{{ checksum "package-lock.json" }}
            - preact-baby-names-cache-
      - run:
          name: Build Production Bundles
          command: npm run build
      - run:
          name: Deploy to S3
          command: aws s3 sync ./dist s3://preact-baby-names --delete

workflows:
  version: 2.1
  build_and_test:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
